FROM ubuntu:16.04

MAINTAINER Wayland Chan <wayland.chan@gmail.com>

LABEL org.waylandc.ide.name="IntelliJ IDEA" org.waylandc.ide.version=2017.1.3

RUN apt-get update && apt-get upgrade -y \
	openjdk-8-jdk \
	openjdk-8-doc

# Replace 1000 with your user / group id
RUN export uid=1000 gid=1000 && \
	mkdir -p /etc/sudoers.d && \
	echo "wchan:x:${uid}:${gid}:Wayland,,,:/home/wchan:/bin/bash" >> /etc/passwd && \
	echo "wchan:x:${uid}:" >> /etc/group && \
	echo "wchan ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/wchan && \
	chmod 0440 /etc/sudoers.d/wchan 
#chown ${uid}:${gid} -R /home/wchan 

ADD https://download.jetbrains.com/idea/ideaIU-2017.1.3.tar.gz /tmp/ideaIU-2017.1.3.tar.gz

RUN mkdir -p /opt/intellij && \
	tar zxf /tmp/ideaIU-2017.1.3.tar.gz --strip-components=1 -C /opt/intellij && \
	rm /tmp/ideaIU-2017.1.3.tar.gz

ENV IDEA_JDK=/usr/lib/jvm/open-jdk
USER wchan
ENV HOME /home/wchan
WORKDIR /home/wchan


#ENTRYPOINT ["/opt/intellij/bin/idea.sh"]
CMD ["/bin/bash"]


