FROM ubuntu:16.04

MAINTAINER Wayland Chan <wayland.chan@gmail.com>

LABEL org.waylandc.ide.name="IntelliJ Gogland" org.waylandc.ide.version=2017.1.3

RUN apt-get update && apt-get upgrade -y \
	openjdk-8-jdk \
	openjdk-8-doc

# Replace 1000 with your user / group id
RUN export uid=1000 gid=1000 && \
	mkdir -p /etc/sudoers.d && \
	echo "wchan:x:${uid}:${gid}:Wayland,,,:/home/wchan:/bin/bash" >> /etc/passwd && \
	echo "wchan:x:${uid}:" >> /etc/group && \
	echo "wchan ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/wchan && \
	chmod 0440 /etc/sudoers.d/wchan 
#chown ${uid}:${gid} -R /home/wchan 

ADD https://download.jetbrains.com/go/gogland-171.4424.55.tar.gz /tmp/gogland.tar.gz


RUN mkdir -p /opt/gogland && \
	tar zxf /tmp/gogland.tar.gz --strip-components=1 -C /opt/gogland && \
	rm /tmp/gogland.tar.gz

ADD https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz golang.tar.gz

RUN tar -zxvf golang.tar.gz -C /usr/local

ENV HOME /home/wchan
ENV PATH="${PATH}:/usr/local/go/bin"
ENV GOROOT=$HOME/go
USER wchan
WORKDIR /home/wchan


CMD ["/bin/bash"]


